//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbsApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pbsEntities : DbContext
    {
        public pbsEntities()
            : base("name=pbsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sys_code> sys_code { get; set; }
        public virtual DbSet<sys_unit> sys_unit { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<login_info> login_info { get; set; }
        public virtual DbSet<ticketauth> ticketauth { get; set; }
        public virtual DbSet<sys_version> sys_version { get; set; }
        public virtual DbSet<investigate_info> investigate_info { get; set; }
        public virtual DbSet<privilege> privilege { get; set; }
        public virtual DbSet<sys_button> sys_button { get; set; }
        public virtual DbSet<sys_data> sys_data { get; set; }
        public virtual DbSet<sys_menu> sys_menu { get; set; }
        public virtual DbSet<sys_role> sys_role { get; set; }
        public virtual DbSet<sys_userrole> sys_userrole { get; set; }
        public virtual DbSet<wx_user> wx_user { get; set; }
        public virtual DbSet<view_record2word> view_record2word { get; set; }
        public virtual DbSet<view_report> view_report { get; set; }
        public virtual DbSet<view_userhasrole> view_userhasrole { get; set; }
        public virtual DbSet<record_info> record_info { get; set; }
        public virtual DbSet<trace_info> trace_info { get; set; }
        public virtual DbSet<view_recordinfo> view_recordinfo { get; set; }
        public virtual DbSet<view_trace_info> view_trace_info { get; set; }
        public virtual DbSet<pbs_record> pbs_record { get; set; }
        public virtual DbSet<sys_upload_file> sys_upload_file { get; set; }
    }
}
