//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbs_record
    {
        public int record_id { get; set; }
        public string uuid { get; set; }
        public string record_title { get; set; }
        public Nullable<int> ky_unit { get; set; }
        public Nullable<int> bg_unit { get; set; }
        public Nullable<System.DateTime> ky_date { get; set; }
        public Nullable<int> jjr { get; set; }
        public Nullable<System.DateTime> bj_time { get; set; }
        public string bjr { get; set; }
        public Nullable<int> bjr_sex { get; set; }
        public string bjr_idcard { get; set; }
        public string bjr_phoneNo { get; set; }
        public string fs_loc { get; set; }
        public string xz { get; set; }
        public Nullable<System.DateTime> kyks_time { get; set; }
        public Nullable<System.DateTime> kyjs_time { get; set; }
        public string xc_loc { get; set; }
        public string xc_locpt { get; set; }
        public Nullable<sbyte> bh_flag { get; set; }
        public Nullable<int> bhr { get; set; }
        public string bhr_pos { get; set; }
        public string bh_function { get; set; }
        public string xc_info { get; set; }
        public string bd_reason { get; set; }
        public string weather_info { get; set; }
        public string temper_info { get; set; }
        public string humidity_info { get; set; }
        public string trend_info { get; set; }
        public string light_info { get; set; }
        public Nullable<int> zhr { get; set; }
        public Nullable<int> zhr_unit { get; set; }
        public string zhr_pos { get; set; }
        public string xc_disp { get; set; }
        public Nullable<int> blr { get; set; }
        public Nullable<int> ztr { get; set; }
        public Nullable<int> zxr { get; set; }
        public Nullable<int> lxr { get; set; }
        public Nullable<int> lyr { get; set; }
        public string jzr { get; set; }
        public Nullable<int> creater_id { get; set; }
        public Nullable<int> record_state { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string check_hint { get; set; }
        public Nullable<int> dest_unit { get; set; }
        public string record_no { get; set; }
        public string jjr_other { get; set; }
        public Nullable<int> bhr_unit { get; set; }
        public string record_reason { get; set; }
        public string doc_url { get; set; }
        public string zhr_name { get; set; }
        public string zhr_unit_name { get; set; }
        public string blr_name { get; set; }
        public string ztr_name { get; set; }
        public string zxr_name { get; set; }
        public string lxr_name { get; set; }
        public string lyr_name { get; set; }
        public string bhr_name { get; set; }
        public string bhr_unit_name { get; set; }
        public string east { get; set; }
        public string west { get; set; }
        public string south { get; set; }
        public string north { get; set; }
        public string jzr_sex { get; set; }
        public string jzr_birth { get; set; }
        public string jzr_address { get; set; }
        public string record_ky_no { get; set; }
        public string record_jj_no { get; set; }
        public string record_aj_no { get; set; }
        public Nullable<System.DateTime> af_time { get; set; }
    }
}
