//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_unit
    {
        public int unit_id { get; set; }
        public string unit_name { get; set; }
        public Nullable<sbyte> is_top { get; set; }
        public Nullable<int> father_unit_id { get; set; }
        public string unit_full_name { get; set; }
        public string bg_dot_name { get; set; }
    }
}
