//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_upload_file
    {
        public int file_id { get; set; }
        public string file_name { get; set; }
        public string file_hint { get; set; }
        public string file_url { get; set; }
        public Nullable<int> file_uploader { get; set; }
        public Nullable<System.DateTime> file_upload_time { get; set; }
        public Nullable<int> record_id { get; set; }
        public Nullable<int> file_type { get; set; }
        public string rec_uuid { get; set; }
    }
}
