//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_fullname { get; set; }
        public string user_pwd { get; set; }
        public Nullable<int> user_state { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> unit_id { get; set; }
        public string user_zw { get; set; }
        public string openId { get; set; }
        public string avatar_url { get; set; }
    }
}
