//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trace_info
    {
        public int sid { get; set; }
        public string uuid { get; set; }
        public string name { get; set; }
        public string trace_type { get; set; }
        public string tqbw { get; set; }
        public string disp { get; set; }
        public Nullable<int> create_id { get; set; }
        public string image1 { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string barcode { get; set; }
    }
}
