//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.QuickStart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class sys_unit
    {
        public int unit_id { get; set; }
        [Display(Name = "名称")]
        [Required]
        public string unit_name { get; set; }
        [Display(Name = "是否顶层单位")]
        [Required]
        public Nullable<sbyte> is_top { get; set; }
        [Display(Name = "上级单位")]
        public Nullable<int> father_unit_id { get; set; }
        [Display(Name = "单位全称")]
        public string unit_full_name { get; set; }
        [Display(Name = "模板名称")]
        public string bg_dot_name { get; set; }
    }
}
