//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.QuickStart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketauth
    {
        public int ticket_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> expire_time { get; set; }
        public Nullable<int> state { get; set; }
        public string client_ip { get; set; }
        public Nullable<int> user_type { get; set; }
    }
}
