//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.QuickStart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_recordinfo
    {
        public int sid { get; set; }
        public string uuid { get; set; }
        public string recordNo { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<int> creatorId { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> type { get; set; }
        public string recordLoc { get; set; }
        public string recordType { get; set; }
        public string locName { get; set; }
        public string locDisp { get; set; }
        public string openId { get; set; }
        public string creatorName { get; set; }
        public string creatorFullName { get; set; }
        public string avatarUrl { get; set; }
    }
}
