//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.QuickStart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_trace_info
    {
        public int sid { get; set; }
        public string uuid { get; set; }
        public string name { get; set; }
        public string traceType { get; set; }
        public string tqbw { get; set; }
        public string disp { get; set; }
        public Nullable<int> creatorId { get; set; }
        public string image1 { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string barcode { get; set; }
        public string creatorName { get; set; }
        public string openId { get; set; }
        public string creatorFullName { get; set; }
        public string avatarUrl { get; set; }
    }
}
