//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.QuickStart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_user
    {
        public int sid { get; set; }
        public string wx_id { get; set; }
        public string wx_name { get; set; }
        public string real_name { get; set; }
        public Nullable<int> unit_id { get; set; }
        public string position { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string avatar_url { get; set; }
        public string unit_name { get; set; }
    }
}
